### ISSUE TITLE
Another compilation error

### ISSUE THREAD

**Issue by kategray** [ANSSI-FR/SmartPGP#26]
I believe this is related to the Gradle version.

```
kate@Kates-MacBook-Pro SmartPGP-1.16-3.0.4 % gradle convertJavacard --info 
Initialized native services in: /Users/kate/.gradle/native
The client will now receive all logging from the daemon (pid: 56906). The daemon log file: /Users/kate/.gradle/daemon/6.7.1/daemon-56906.out.log
Starting 3rd build in daemon [uptime: 22 mins 48.329 secs, performance: 100%, non-heap usage: 22% of 268.4 MB]
Using 16 worker leases.
Watching the file system is disabled
Starting Build
Settings evaluated using settings file '/Users/kate/Downloads/SmartPGP-1.16-3.0.4/settings.gradle'.
Projects loaded. Root project using build file '/Users/kate/Downloads/SmartPGP-1.16-3.0.4/build.gradle'.
Included projects: [root project 'SmartPGP-1.16-3.0.4']

> Configure project :
Evaluating root project 'SmartPGP-1.16-3.0.4' using build file '/Users/kate/Downloads/SmartPGP-1.16-3.0.4/build.gradle'.
All projects evaluated.
Selected primary task 'convertJavacard' from project :

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':convertJavacard'.
> Could not get unknown property 'classesDir' for main classes of type org.gradle.api.internal.tasks.DefaultSourceSetOutput.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 546ms
```

```
kate@Kates-MacBook-Pro SmartPGP-1.16-3.0.4 % java --version
openjdk 11.0.8 2020-07-14 LTS
OpenJDK Runtime Environment Corretto-11.0.8.10.1 (build 11.0.8+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.8.10.1 (build 11.0.8+10-LTS, mixed mode)
```

**Comment by af-anssi** [comment]
@dschuermann Could you give a hand ?
As an alternative, you can use the ant build system.

**Comment by dschuermann** [comment]
I also switched to the ant system by martinpaljak as it's more maintained :see_no_evil: .

**Comment by af-anssi** [comment]
@kategray could you confirm you have no problem with the `ant` build ?
I will remove the `gradle` since ti is not maintained anymore.

**Comment by af-anssi** [comment]
I close the issue since the `gradle` build is not supported anymore.
